s3:
    access_key_id: '*'
    secret_access_key: '*'
    bucket_name: 'busphoto'

image_settings:
    horizontal_res: 640
    vertical_res: 480
    file_name: 'test'
    file_extension: '.jpg'
    folder_name: 'images'
    awb_mode: 'auto'
    photo_interval: 1000

debug: true


